# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: wednesday
      time: "06:00"
      timezone: "Asia/Taipei"
    assignees:
      - "1chooo"
    open-pull-requests-limit: 10
    groups:
      nextjs:
        patterns:
          - "next"
          - "@next/*"
        update-types:
          - "minor"
          - "patch"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
        update-types:
          - "minor"
          - "patch"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "eslint-plugin-*"
          - "eslint"
          - "typescript-eslint"
        update-types:
          - "minor"
          - "patch"
      vitest:
        patterns:
          - "vitest"
          - "@vitejs/plugin-react" 
          - "jsdom"
          - "@testing-library/*" 
          - "vite-tsconfig-paths"
        update-types:
          - "minor"
          - "patch"
      shiki:
        patterns:
          - "shiki"
          - "@shikijs/rehype"
        update-types:
          - "minor"
          - "patch"

